### ISSUE TITLE
这么几行代码你就实现你视频上的功能了么？求详细解释

### ISSUE THREAD

**Issue by sheldon123z** [chengyou-jia/AgentStore#1]
你确定你视频里那个cli的操作不是人录制的？那机器还能打错字回退呢？

**Comment by chengyou-jia** [comment]
视频内的演示不是目前代码跑的，正常的demo和代码正在更新，下周就会推送

**Comment by chengyou-jia** [comment]
网站展示的例子都是agentstore可以成功完成的，因为agent输出打字太快，很难录制，所以才用先用人工的表示，请等待更新后试用对应的例子。

**Comment by sheldon123z** [comment]
好的，那是我误解了，我以为又碰见了假文章，一时气愤，那就期待更新。
